version: '3'
services:
  server:
    container_name: server
    image: texastoc-v4-h2-image:latest
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "use": {
            "h2": true,
            "mysql": false
          },
          "populate": true,
          "allowMultipleSeasons": false
        }
    ports:
      - 8080:8080
