version: '3'
services:
  db:
    container_name: db
    image: 'mysql:8.0.25'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - './data:/var/lib/mysql'
